# Generated by Django 6.0.5 on 2026-06-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Tool', 'Tool'), ('Platform', 'Platform'), ('Sokt skill', 'Sokt skill'), ('Database', 'Database')], max_length=50)),
            ],
        ),
    ]
