# Generated by Django 6.0.5 on 2026-05-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='demo_link',
            field=models.URLField(null=True),
        ),
    ]
