# Generated by Django 6.0.5 on 2026-06-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_demo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
